version: "3"
services:
    # the service name can be given anything
    # give names that are easily understandable
    react-app:
        environment: 
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - ./:/app
    
    tests:
        environment: 
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./:/app
        command: ["npm", "run", "test"]